language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: max.mykhailenko@gmail.com
  on:
    tags: true
    repo: memCrab/eslint-config-memcrab
    branch: main